version: '3.9'
services:
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - D:/apps/docker_data/redis/data:/data
    restart: always
